Allow all ssl certs
- Tumblr seems to host its _raw images (now) on amazon S3 but forgot to
update the ssl cert, thus all connections fail. The error message is:

Security.Authentication.AuthenticationException: The remote certificate
is invalid according to the validation procedure

We now just temporarily trust all certs until it's fixed.